// apps/web/src/lib/components/dashboard/MetricGrid.svelte
<script lang="ts">
	import EmptyState from '$lib/components/ui/EmptyState.svelte';
	import ErrorState from '$lib/components/ui/ErrorState.svelte';
	import LoadingState from '$lib/components/ui/LoadingState.svelte';
	import MetricCard from '$lib/components/dashboard/MetricCard.svelte';
	import type { LoadState } from '$lib/types/common';
	import type { Metric } from '$lib/types/dashboard';

	let {
		metrics,
		state = 'ready',
		onretry
	}: { metrics: Metric[]; state?: LoadState; onretry?: () => void } = $props();
</script>

{#if state === 'loading'}
	<LoadingState label="Loading performance metrics..." />
{:else if state === 'error'}
	<ErrorState description="Metrics could not be prepared from the local dataset." {onretry} />
{:else if state === 'empty' || metrics.length === 0}
	<EmptyState
		description="Run a simulation to see customer volume, conversations, purchase rate, and repeat rate."
		title="No metrics yet"
	/>
{:else}
	<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
		{#each metrics as metric (metric.label)}
			<MetricCard {metric} />
		{/each}
	</div>
{/if}

// apps/next-prototype/src/components/dashboard/MetricGrid.tsx
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingState } from "@/components/ui/LoadingState";
import { MetricCard } from "@/components/dashboard/MetricCard";
import type { LoadState, Metric } from "@/types/dashboard";

type MetricGridProps = {
  metrics: Metric[];
  state?: LoadState;
};

export function MetricGrid({ metrics, state = "ready" }: MetricGridProps) {
  if (state === "loading") {
    return <LoadingState label="Loading performance metrics..." />;
  }

  if (state === "error") {
    return <ErrorState description="Metrics could not be prepared from the local dataset." />;
  }

  if (state === "empty" || metrics.length === 0) {
    return (
      <EmptyState
        description="Run a simulation to see customer volume, conversations, purchase rate, and repeat rate."
        title="No metrics yet"
      />
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {metrics.map((metric) => (
        <MetricCard key={metric.label} metric={metric} />
      ))}
    </div>
  );
}
