// apps/web/src/lib/components/reports/FeedbackPanel.svelte
<script lang="ts">
	import { CheckCircle2 } from 'lucide-svelte';
	import Card from '$lib/components/ui/Card.svelte';

	let { title, items }: { title: string; items: string[] } = $props();
</script>

<Card class="p-5">
	<h2 class="text-sm font-semibold text-slate-100">{title}</h2>
	<ul class="mt-4 space-y-3">
		{#each items as item (item)}
			<li class="flex items-start gap-3 text-xs leading-5 text-slate-300">
				<CheckCircle2
					aria-hidden="true"
					class="mt-0.5 shrink-0 text-green-400"
					size={14}
					strokeWidth={1.8}
				/>
				{item}
			</li>
		{/each}
	</ul>
</Card>

// src/components/reports/FeedbackPanel.tsx
import { Card } from "@/components/ui/Card";

type FeedbackPanelProps = {
  title: string;
  items: string[];
};

export function FeedbackPanel({ title, items }: FeedbackPanelProps) {
  return (
    <Card className="p-5">
      <h2 className="text-lg font-semibold text-slate-100">{title}</h2>
      <ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">
        {items.map((item) => (
          <li className="flex gap-3" key={item}>
            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
            {item}
          </li>
        ))}
      </ul>
    </Card>
  );
}
