// apps/next-prototype/src/components/simulations/MessageInput.tsx
import type { FormEvent } from "react";

import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";

type MessageInputProps = {
  value: string;
  error?: string;
  onChange: (value: string) => void;
  onSubmit: () => void;
};

export function MessageInput({ value, error, onChange, onSubmit }: MessageInputProps) {
  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    onSubmit();
  }

  return (
    <form
      className="border-t border-border bg-ink-900/70 px-4 py-4 sm:px-5"
      onSubmit={handleSubmit}
    >
      <div className="flex items-center gap-3">
        <Input
          aria-describedby={error ? "message-error" : undefined}
          aria-label="Type a message"
          onChange={(event) => onChange(event.target.value)}
          placeholder="Type a message..."
          value={value}
        />
        <Button aria-label="Send message" size="icon" type="submit">
          <svg aria-hidden="true" className="h-5 w-5" fill="none" viewBox="0 0 24 24">
            <path
              d="M5 12h13M13 6l6 6-6 6"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
            />
          </svg>
        </Button>
      </div>
      {error ? (
        <p className="mt-2 text-xs font-medium text-red-300" id="message-error">
          {error}
        </p>
      ) : null}
    </form>
  );
}

// apps/web/src/lib/components/simulations/MessageInput.svelte
<script lang="ts">
	import { Send } from 'lucide-svelte';

	import Button from '$lib/components/ui/Button.svelte';
	import Input from '$lib/components/ui/Input.svelte';

	let {
		value,
		error,
		onchange,
		onsubmit
	}: {
		value: string;
		error?: string;
		onchange: (value: string) => void;
		onsubmit: () => void;
	} = $props();

	function handleKeydown(event: KeyboardEvent): void {
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			onsubmit();
		}
	}
</script>

<div class="border-t border-border/80 bg-ink-900/55 p-3">
	<div class="flex items-center gap-2 rounded-lg border border-border bg-ink-950/50 p-1.5">
		<label class="sr-only" for="simulation-message">Type a message</label>
		<Input
			aria-describedby={error ? 'simulation-message-error' : undefined}
			aria-invalid={Boolean(error)}
			class="h-9 border-0 bg-transparent px-3 focus:ring-0"
			id="simulation-message"
			oninput={(event) => onchange(event.currentTarget.value)}
			onkeydown={handleKeydown}
			placeholder="Type a message..."
			{value}
		/>
		<Button
			aria-label="Send message"
			disabled={!value.trim()}
			onclick={onsubmit}
			size="icon"
			class="h-9 w-9 rounded-full"
		>
			<Send aria-hidden="true" size={17} />
		</Button>
	</div>
	{#if error}
		<p class="mt-2 text-xs text-red-300" id="simulation-message-error" role="alert">{error}</p>
	{/if}
</div>
