// apps/web/src/lib/components/layout/MobileNav.svelte
<script lang="ts">
	import { Menu, X } from 'lucide-svelte';
	import { resolve } from '$app/paths';

	import LogoMark from '$lib/components/layout/LogoMark.svelte';
	import Sidebar from '$lib/components/layout/Sidebar.svelte';
	import { APP_NAME } from '$lib/constants/app';

	let { activePath }: { activePath: string } = $props();
</script>

<header
	class="sticky top-0 z-40 flex h-16 w-full items-center justify-between border-b border-border/90 bg-ink-950/92 px-4 backdrop-blur-xl lg:hidden"
>
	<a class="flex items-center gap-3" href={resolve('/dashboard')}>
		<LogoMark />
		<span class="text-sm font-bold text-slate-100">{APP_NAME}</span>
	</a>
	<button
		aria-label="Open navigation menu"
		class="grid h-10 w-10 shrink-0 place-items-center rounded-md border border-border bg-ink-800/70 text-slate-100 transition hover:border-brand-light/55 hover:bg-brand/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-light focus-visible:ring-offset-2 focus-visible:ring-offset-ink-950"
		popovertarget="mobile-navigation-drawer"
		type="button"
	>
		<Menu aria-hidden="true" size={19} />
	</button>
</header>

<div
	aria-label="Mobile navigation drawer"
	class="m-0 h-dvh max-h-none w-[min(20rem,86vw)] max-w-none border-0 bg-transparent p-0"
	id="mobile-navigation-drawer"
	popover="auto"
>
	<div class="relative h-full">
		<button
			aria-label="Close navigation menu"
			class="absolute top-5 right-4 z-10 grid h-9 w-9 place-items-center rounded-md border border-border bg-ink-800 text-slate-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-light"
			popovertarget="mobile-navigation-drawer"
			popovertargetaction="hide"
			type="button"
		>
			<X aria-hidden="true" size={18} />
		</button>
		<Sidebar {activePath} />
	</div>
</div>

<style>
	#mobile-navigation-drawer:popover-open {
		inset: 0 auto 0 0;
	}

	#mobile-navigation-drawer::backdrop {
		background: rgb(0 0 0 / 68%);
		backdrop-filter: blur(4px);
	}
</style>

// src/components/layout/MobileNav.tsx
"use client";

import { Sidebar } from "@/components/layout/Sidebar";
import { Button } from "@/components/ui/Button";
import { APP_NAME } from "@/constants/app";
import { cn } from "@/lib/utils";

type MobileNavProps = {
  activePath: string;
  isOpen: boolean;
  onClose: () => void;
  onToggle: () => void;
};

export function MobileNav({ activePath, isOpen, onClose, onToggle }: MobileNavProps) {
  return (
    <>
      <header className="sticky top-0 z-40 flex h-16 w-screen max-w-full items-center gap-3 border-b border-border bg-ink-950/88 px-4 backdrop-blur-xl lg:hidden">
        <div className="flex items-center gap-3">
          <span className="grid h-9 w-9 place-items-center rounded-xl border border-brand-light/35 bg-brand-soft text-sm font-bold text-brand-light">
            PM
          </span>
          <span className="text-sm font-bold text-slate-100">{APP_NAME}</span>
        </div>
        <Button
          aria-expanded={isOpen}
          aria-label="Toggle navigation menu"
          className="shrink-0"
          onClick={onToggle}
          size="icon"
          variant="secondary"
        >
          <span className="sr-only">Menu</span>
          <span className="relative block h-4 w-5">
            <span
              className={cn(
                "absolute left-0 top-0 h-0.5 w-5 rounded bg-current transition",
                isOpen && "translate-y-2 rotate-45",
              )}
            />
            <span
              className={cn(
                "absolute left-0 top-2 h-0.5 w-5 rounded bg-current transition",
                isOpen && "opacity-0",
              )}
            />
            <span
              className={cn(
                "absolute left-0 top-4 h-0.5 w-5 rounded bg-current transition",
                isOpen && "-translate-y-2 -rotate-45",
              )}
            />
          </span>
        </Button>
      </header>

      {isOpen ? (
        <div className="fixed inset-0 z-50 lg:hidden">
          <button
            aria-label="Close navigation menu"
            className="absolute inset-0 bg-black/65 backdrop-blur-sm"
            onClick={onClose}
            type="button"
          />
          <div className="absolute inset-y-0 left-0 w-[min(21rem,86vw)]">
            <Sidebar activePath={activePath} onNavigate={onClose} />
          </div>
        </div>
      ) : null}
    </>
  );
}
