// apps/next-prototype/src/components/ui/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from "react";

import { cn } from "@/lib/utils";

type ButtonVariant = "primary" | "secondary" | "ghost";
type ButtonSize = "sm" | "md" | "icon";

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  children: ReactNode;
  variant?: ButtonVariant;
  size?: ButtonSize;
};

const variantClasses: Record<ButtonVariant, string> = {
  primary:
    "bg-brand-purple text-white shadow-[0_6px_16px_rgba(124,58,237,0.16)] hover:bg-brand-light focus-visible:ring-brand-light",
  secondary:
    "border border-border bg-ink-800/70 text-slate-100 hover:border-brand-light/60 hover:bg-brand-soft focus-visible:ring-brand-light",
  ghost:
    "text-slate-300 hover:bg-white/5 hover:text-white focus-visible:ring-brand-light",
};

const sizeClasses: Record<ButtonSize, string> = {
  sm: "h-8 px-3 text-xs",
  md: "h-10 px-4 text-sm",
  icon: "h-10 w-10 p-0",
};

export function Button({
  children,
  className,
  variant = "primary",
  size = "md",
  type = "button",
  ...props
}: ButtonProps) {
  return (
    <button
      className={cn(
        "inline-flex items-center justify-center gap-2 rounded-lg font-semibold transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-ink-950 disabled:cursor-not-allowed disabled:opacity-50",
        variantClasses[variant],
        sizeClasses[size],
        className,
      )}
      type={type}
      {...props}
    >
      {children}
    </button>
  );
}

// apps/web/src/lib/components/ui/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	type Variant = 'primary' | 'secondary' | 'ghost';
	type Size = 'sm' | 'md' | 'icon';

	let {
		children,
		class: className = '',
		variant = 'primary',
		size = 'md',
		type = 'button',
		disabled = false,
		...rest
	}: HTMLButtonAttributes & {
		children: Snippet;
		variant?: Variant;
		size?: Size;
	} = $props();

	const variantClasses: Record<Variant, string> = {
		primary:
			'bg-brand text-white hover:bg-brand-light focus-visible:ring-brand-light shadow-[0_5px_14px_rgba(124,58,237,0.14)]',
		secondary:
			'border border-border bg-ink-800/70 text-slate-100 hover:border-brand-light/55 hover:bg-brand/10 focus-visible:ring-brand-light',
		ghost: 'text-slate-300 hover:bg-white/5 hover:text-white focus-visible:ring-brand-light'
	};

	const sizeClasses: Record<Size, string> = {
		sm: 'h-8 px-3 text-xs',
		md: 'h-10 px-4 text-sm',
		icon: 'h-10 w-10 p-0'
	};
</script>

<button
	{type}
	{disabled}
	class={[
		'inline-flex shrink-0 items-center justify-center gap-2 rounded-md font-semibold transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-ink-950 disabled:cursor-not-allowed disabled:opacity-45',
		variantClasses[variant],
		sizeClasses[size],
		className
	]}
	{...rest}
>
	{@render children()}
</button>
