// src/features/simulations/LiveSimulationScreen.tsx
"use client";

import { useState } from "react";

import { ActivityFeed } from "@/components/simulations/ActivityFeed";
import { ChatThread } from "@/components/simulations/ChatThread";
import { CustomerAgentList } from "@/components/simulations/CustomerAgentList";
import { LiveSimulationHeader } from "@/components/simulations/LiveSimulationHeader";
import { LiveSimulationTabs } from "@/components/simulations/LiveSimulationTabs";
import { MessageInput } from "@/components/simulations/MessageInput";
import { SimulationStats } from "@/components/simulations/SimulationStats";
import { Card } from "@/components/ui/Card";
import { getLiveSimulationData } from "@/services/dummy-data/simulation-data";
import type { ChatMessage, SimulationTabId } from "@/types/simulation";
import { validateMessage } from "@/validation/message";

const simulationData = getLiveSimulationData();

function getCurrentTimeLabel(): string {
  return new Date().toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function LiveSimulationScreen() {
  const [activeTab, setActiveTab] = useState<SimulationTabId>("live-chat");
  const [messages, setMessages] = useState<ChatMessage[]>(simulationData.messages);
  const [draft, setDraft] = useState("");
  const [error, setError] = useState<string | undefined>();

  function handleSendMessage() {
    const result = validateMessage(draft);

    if (!result.valid) {
      setError(result.error);
      return;
    }

    setMessages((currentMessages) => [
      ...currentMessages,
      {
        id: `local-${Date.now()}`,
        sender: "business",
        body: draft.trim(),
        timestamp: getCurrentTimeLabel(),
      },
    ]);
    setDraft("");
    setError(undefined);
  }

  return (
    <Card className="min-h-[calc(100vh-7rem)] overflow-hidden">
      <LiveSimulationHeader
        elapsedTime={simulationData.elapsedTime}
        status={simulationData.status}
        title={simulationData.title}
      />
      <LiveSimulationTabs activeTab={activeTab} onTabChange={setActiveTab} />

      {activeTab === "live-chat" ? (
        <div className="grid min-h-[34rem] md:grid-cols-[20rem_1fr]">
          <CustomerAgentList agents={simulationData.agents} />
          <div className="flex min-w-0 flex-col">
            <ChatThread messages={messages} />
            <MessageInput
              error={error}
              onChange={(value) => {
                setDraft(value);
                if (error) {
                  setError(undefined);
                }
              }}
              onSubmit={handleSendMessage}
              value={draft}
            />
          </div>
        </div>
      ) : null}

      {activeTab === "customer-agents" ? (
        <SimulationStats agents={simulationData.agents} stats={simulationData.stats} />
      ) : null}

      {activeTab === "activity-feed" ? (
        <ActivityFeed activity={simulationData.activity} />
      ) : null}

      {activeTab === "simulation-stats" ? (
        <SimulationStats stats={simulationData.stats} />
      ) : null}
    </Card>
  );
}

// apps/web/src/lib/features/simulations/LiveSimulationScreen.svelte
<script lang="ts">
	import ActivityFeed from '$lib/components/simulations/ActivityFeed.svelte';
	import ChatThread from '$lib/components/simulations/ChatThread.svelte';
	import CustomerAgentList from '$lib/components/simulations/CustomerAgentList.svelte';
	import LiveSimulationHeader from '$lib/components/simulations/LiveSimulationHeader.svelte';
	import MessageInput from '$lib/components/simulations/MessageInput.svelte';
	import SimulationStats from '$lib/components/simulations/SimulationStats.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import Tabs from '$lib/components/ui/Tabs.svelte';
	import { simulationTabs } from '$lib/constants/tabs';
	import { getLiveSimulationData } from '$lib/data/simulation';
	import type { ChatMessage, SimulationTabId } from '$lib/types/simulation';
	import { getCurrentTimeLabel } from '$lib/utils/format';
	import { validateMessage } from '$lib/validation/message';

	const simulationData = getLiveSimulationData();

	let activeTab = $state<SimulationTabId>('live-chat');
	let activeAgentId = $state(simulationData.agents[0]?.id ?? '');
	let messages = $state<ChatMessage[]>([...simulationData.messages]);
	let draft = $state('');
	let error = $state<string | undefined>();

	function handleTabChange(tab: string): void {
		activeTab = tab as SimulationTabId;
	}

	function handleSendMessage(): void {
		const result = validateMessage(draft);

		if (!result.valid) {
			error = result.error;
			return;
		}

		messages = [
			...messages,
			{
				id: `local-${Date.now()}`,
				sender: 'business',
				body: draft.trim(),
				timestamp: getCurrentTimeLabel()
			}
		];
		draft = '';
		error = undefined;
	}
</script>

<Card class="overflow-hidden">
	<LiveSimulationHeader
		elapsedTime={simulationData.elapsedTime}
		status={simulationData.status}
		title={simulationData.title}
	/>
	<Tabs
		{activeTab}
		ariaLabel="Live simulation views"
		onchange={handleTabChange}
		tabs={simulationTabs}
	/>

	{#if activeTab === 'live-chat'}
		<div class="grid min-h-[34rem] min-w-0 max-w-full md:grid-cols-[19rem_minmax(0,1fr)]">
			<CustomerAgentList
				{activeAgentId}
				agents={simulationData.agents}
				onselect={(id) => (activeAgentId = id)}
			/>
			<div class="flex min-w-0 flex-col">
				<ChatThread {messages} />
				<MessageInput
					{error}
					onchange={(value) => {
						draft = value;
						if (error) error = undefined;
					}}
					onsubmit={handleSendMessage}
					value={draft}
				/>
			</div>
		</div>
	{:else if activeTab === 'customer-agents'}
		<SimulationStats agents={simulationData.agents} stats={simulationData.stats} />
	{:else if activeTab === 'activity-feed'}
		<ActivityFeed activity={simulationData.activity} />
	{:else}
		<SimulationStats stats={simulationData.stats} />
	{/if}
</Card>
