// apps/web/src/lib/components/reports/ObjectionPanel.svelte
<script lang="ts">
	import { CircleAlert } from 'lucide-svelte';
	import Card from '$lib/components/ui/Card.svelte';

	let { title, items }: { title: string; items: string[] } = $props();
</script>

<Card class="p-5">
	<h2 class="text-sm font-semibold text-red-300">{title}</h2>
	<ul class="mt-4 space-y-3">
		{#each items as item (item)}
			<li class="flex items-start gap-3 text-xs leading-5 text-slate-300">
				<CircleAlert
					aria-hidden="true"
					class="mt-0.5 shrink-0 text-red-400"
					size={14}
					strokeWidth={1.8}
				/>
				{item}
			</li>
		{/each}
	</ul>
</Card>

// apps/next-prototype/src/components/reports/ObjectionPanel.tsx
import { Card } from "@/components/ui/Card";

type ObjectionPanelProps = {
  title: string;
  items: string[];
};

export function ObjectionPanel({ title, items }: ObjectionPanelProps) {
  return (
    <Card className="p-5">
      <h2 className="text-lg font-semibold text-red-300">{title}</h2>
      <ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">
        {items.map((item) => (
          <li className="flex gap-3" key={item}>
            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-red-300" />
            {item}
          </li>
        ))}
      </ul>
    </Card>
  );
}
