// apps/web/src/lib/components/simulations/SimulationStats.svelte
<script lang="ts">
	import type { CustomerAgent, SimulationStat } from '$lib/types/simulation';

	let { stats, agents = [] }: { stats: SimulationStat[]; agents?: CustomerAgent[] } = $props();
</script>

<div class="p-5">
	<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
		{#each stats as stat (stat.label)}
			<article class="rounded-lg border border-border bg-ink-900/38 p-5">
				<p class="text-xs font-medium text-slate-400">{stat.label}</p>
				<p class="mt-3 text-2xl font-bold text-brand-light">{stat.value}</p>
				<p class="mt-2 text-xs leading-5 text-slate-500">{stat.detail}</p>
			</article>
		{/each}
	</div>

	{#if agents.length > 0}
		<div class="mt-5 rounded-lg border border-border bg-ink-900/30 p-5">
			<h2 class="text-sm font-semibold text-slate-100">Customer agents in this simulation</h2>
			<div class="mt-4 flex flex-wrap gap-3">
				{#each agents as agent (agent.id)}
					<div
						class="flex items-center gap-2 rounded-md border border-border bg-ink-950/45 px-3 py-2"
					>
						<img
							alt={agent.avatarAlt}
							class="h-7 w-7 rounded-full"
							height="28"
							src={agent.avatarSrc}
							width="28"
						/>
						<span class="text-xs text-slate-200">{agent.name}, {agent.age}</span>
					</div>
				{/each}
			</div>
		</div>
	{/if}
</div>

// apps/next-prototype/src/components/simulations/SimulationStats.tsx
import Image from "next/image";

import { Card } from "@/components/ui/Card";
import type { CustomerAgent, SimulationStat } from "@/types/simulation";

type SimulationStatsProps = {
  stats: SimulationStat[];
  agents?: CustomerAgent[];
};

export function SimulationStats({ stats, agents }: SimulationStatsProps) {
  return (
    <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-4">
      {agents
        ? agents.map((agent) => (
            <Card className="p-4" key={agent.id}>
              <div className="flex items-center gap-3">
                <Image
                  alt={agent.avatarAlt}
                  className="h-10 w-10 shrink-0 rounded-full border border-border bg-ink-800 object-cover"
                  height={40}
                  src={agent.avatarSrc}
                  unoptimized
                  width={40}
                />
                <div>
                  <p className="font-semibold text-slate-100">
                    {agent.name} <span className="text-slate-500">(Age {agent.age})</span>
                  </p>
                  <p className="mt-1 text-xs text-slate-400">{agent.preview}</p>
                </div>
              </div>
            </Card>
          ))
        : stats.map((stat) => (
            <Card className="p-5" key={stat.label}>
              <p className="text-xs font-medium text-slate-400">{stat.label}</p>
              <p className="mt-3 text-3xl font-bold text-brand-light">{stat.value}</p>
              <p className="mt-2 text-sm leading-6 text-slate-400">{stat.detail}</p>
            </Card>
          ))}
    </div>
  );
}
